# Generated by Django 4.1.2 on 2022-11-09 23:32

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='duration',
            new_name='exercise_times',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='training_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_title',
            field=django_mysql.models.EnumField(choices=[('HITT', 'Hiit'), ('YOGA', 'Yoga'), ('CARDIO', 'Cardio'), ('BOOTY', 'Booty'), ('AB_WORKOUT', 'Ab Workout'), ('WAIST', 'Waist'), ('CIRCUIT', 'Circuit'), ('STRENGTH', 'Strength'), ('FAT_BURNING', 'Fat Burning')], default='HITT'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=django_mysql.models.EnumField(choices=[('ENTRY', 'Entry'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='ENTRY'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=django_mysql.models.EnumField(choices=[('AGE_RANGE_0_29', 'Age Range 0 29'), ('AGE_RANGE_30_40', 'Age Range 30 40'), ('AGE_RANGE_40_50', 'Age Range 40 50'), ('AGE_ABOVE_50', 'Age Above 50'), ('UNDEFINED', 'Undefined')], default='UNDEFINED'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=django_mysql.models.EnumField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNDEFINED', 'Undefined')], default='UNDEFINED'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=django_mysql.models.EnumField(choices=[('ENTRY', 'Entry'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='ENTRY'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
