# Generated by Django 4.1.2 on 2022-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_duration_eventdata_exercise_times_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.AddField(
            model_name="userprofile",
            name="user_id",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.DeleteModel(name="EventData",),
        migrations.DeleteModel(name="User",),
    ]
