# Generated by Django 4.1.2 on 2022-11-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_userprofile_user_userprofile_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_times", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.exercise"
                    ),
                ),
            ],
        ),
    ]
